### ISSUE TITLE
error from community

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/nodebb-plugin-link-preview#10]
```
2023-07-09T19:36:00.160Z [4568/2550175] - ^[[31merror^[[39m: GET /api/topic/17340/testing-thumb-editing/1?_=1688931104569
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at URL.onParseError (node:internal/url:566:9)
    at new URL (node:internal/url:646:5)
    at handleSpecialEmbed (/home/saas/nodebb/node_modules/nodebb-plugin-link-preview/library.js:168:47)
    at process (/home/saas/nodebb/node_modules/nodebb-plugin-link-preview/library.js:63:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async plugin.onParse [as method] (/home/saas/nodebb/node_modules/nodebb-plugin-link-preview/library.js:199:30)
    at async fireMethod (/home/saas/nodebb/src/plugins/hooks.js:164:11)
    at async Object.fireFilterHook [as filter] (/home/saas/nodebb/src/plugins/hooks.js:195:12)
    at async Hooks.fire (/home/saas/nodebb/src/plugins/hooks.js:132:17)


```

**Comment by julianlam** [comment]
What was the url supplied?

**Comment by barisusakli** [comment]
Not sure, happened when trying to ajaxify to this topic https://community.nodebb.org/topic/17340/testing-thumb-editing, which doesn't have any urls 😆

**Comment by barisusakli** [comment]
Another one this one can be reproed 100% 

https://community.nodebb.org/topic/16020/redirect-user-to-email-registration/1

```
2023-07-23T19:59:02.495Z [4568/2725747] - [31merror[39m: GET /topic/16020/redirect-user-to-email-registration/1
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at URL.onParseError (node:internal/url:566:9)
    at new URL (node:internal/url:646:5)
    at handleSpecialEmbed (/home/saas/nodebb/node_modules/nodebb-plugin-link-preview/library.js:168:47)
    at process (/home/saas/nodebb/node_modules/nodebb-plugin-link-preview/library.js:63:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async plugin.onParse [as method] (/home/saas/nodebb/node_modules/nodebb-plugin-link-preview/library.js:199:30)
    at async fireMethod (/home/saas/nodebb/src/plugins/hooks.js:164:11)
    at async Object.fireFilterHook [as filter] (/home/saas/nodebb/src/plugins/hooks.js:195:12)
    at async Hooks.fire (/home/saas/nodebb/src/plugins/hooks.js:132:17)
```
